import struct
import pyodbc

db_token = b'eyJ0eXAiOiJKV1QiLCJub25jZSI6ImM1alRyNS1xaWx5Tlo4ZkwwaFRROVZsRVRwcnVrLTVVYzRZMUlFUFFnRXciLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8xMTUxMjUyNi03YTcyLTRkNDEtOGJjYS0zNWJkMDI3Njg1YTMvIiwiaWF0IjoxNjgwMTYwMjU0LCJuYmYiOjE2ODAxNjAyNTQsImV4cCI6MTY4MDE2NDQwOSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhUQUFBQUVCWVF5SEJHYjRETVFockdNbzdMTUh0TTdTbmFSakFTRXE5YUtCc0EzTHJldWJ5V3RxYktjV2ZLS1ozcWJyM0l3NkxFclpRY2k4UVU5NEduNmlyWHp6RERXYkxxVVMwc1owME1EREpiR1E4PSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwX2Rpc3BsYXluYW1lIjoiYXp1ciBTUUwgZGIxIiwiYXBwaWQiOiIyZTFkMGI2Yy1kZTg4LTQ5ZDMtOGQ4ZS0wYzI3NzJhM2QwMTQiLCJhcHBpZGFjciI6IjEiLCJmYW1pbHlfbmFtZSI6IkFiaXRvbCIsImdpdmVuX25hbWUiOiJCcnVubyIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjMxLjEyNC4xNS4yMiIsIm5hbWUiOiJCcnVubyBBYml0b2wiLCJvaWQiOiJkNzFkOTk0OS1jMzA2LTQ3YTgtODA4Zi1hNTY2ZmRlYTFkMzMiLCJwbGF0ZiI6IjgiLCJwdWlkIjoiMTAwMzIwMDI4Qzc5NjE4QSIsInJoIjoiMC5BVTRBSmlWUkVYSjZRVTJMeWpXOUFuYUZvd01BQUFBQUFBQUF3QUFBQUFBQUFBQ0RBTzguIiwic2NwIjoib3BlbmlkIHByb2ZpbGUgVXNlci5SZWFkQmFzaWMuQWxsIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoia0F5bDNVM0UybUY1bG1SYWJFNElIaVpGUUVTbDc4cTA3VmIzSy10UE9aUSIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJFVSIsInRpZCI6IjExNTEyNTI2LTdhNzItNGQ0MS04YmNhLTM1YmQwMjc2ODVhMyIsInVuaXF1ZV9uYW1lIjoiQnJ1bm9BQHBvc2l0ZGV2LmNvLnVrIiwidXBuIjoiQnJ1bm9BQHBvc2l0ZGV2LmNvLnVrIiwidXRpIjoiRDFzLW9rRzFmMDZQalZybVBZa0dBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiIyMnVaX3lkenFuYjkzTzR4WEZUb0tZdFJRNkxZb3V2NzM2Q1ZlM3NRczVBIn0sInhtc190Y2R0IjoxNjc3NzQzMDAzfQ.PBY9L658oaqtuGNLt2n99SYgLHtrOobsIT_yFp8LMVQbRMisTok8R9WzfC_94k5ma31U0aMgpTMYgYrJhSHvhwPzKRTXctQzjqK4ivZbAvMAeWFzZJTFgMKGvveJ8RzUAM9aCK19EauNwdInOfc0tsUDbM4EQ2zk6sKClNYvPGR5PZqeSRy3beHjnwigVN-OqwddxswnL8-ZwkE9rEE_iTORxkgEX1d9RWuNGgo3nGEkNpfoSJEGO0WDaTXVbQ1PzGLvdHw-XCS0A6QpCS6BZdDOlm_fmqo8wnB50SB_8eP5Yh88eOgOlPRmjwVu4jMyHtZbh3fguyJT7PGB1zGhZw'

connect_string = "Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.10.so.2.1;Server=tcp:postitdev-db1.database.windows.net;Database=Db1;"

exptoken = b''
for i in db_token:
    exptoken += bytes({i})
    exptoken += bytes(1)
tokenstruct = struct.pack("=i", len(exptoken)) + exptoken
conn = pyodbc.connect(connect_string, attrs_before={1256: tokenstruct})
with conn.cursor() as cursor:
    cursor.execute("SELECT getdate()")
    row = cursor.fetchone()
    print(row[0])
